---
- hosts: all
  connection: local
  become: true
  # Init vars to be replaced in general role
  vars:
    zone: IL-HA
    email: nobody@omc.co.il
    adminemail: "{{ email }}"
    password: verysecurerandompassword

  pre_tasks:

    - name: Get collection
      ansible.builtin.command: ansible-galaxy collection install -r requirements.yml
      delegate_to: localhost
      changed_when: false
      tags: always

  tasks:
    - name: Running {{ service }}
      ansible.builtin.include_tasks: "services/{{ service }}.yml"
      when: service is defined

  # post_tasks:
  # - name: Reboot the machine with all defaults using Ansible
  #   ansible.builtin.command: reboot
  #     # msg: "Server rebooted"
