---
# roles:
#   - name: geerlingguy.apache

collections:
  - type: url
    source: https://github.com/pincher95/ansible-pull-collection-test/releases/download/v0.0.1/pincher95-cloudwm_collection-1.0.2.tar.gz
  - name: community.general