---
collections:
  - type: url
    # version: v1.0.5-rc1
    source: https://github.com/pincher95/ansible-pull-collection-test/releases/download/v1.0.6/pincher95-ansible_cloudwm_collection-1.0.6.tar.gz
