---
- name: ClusterControl service
  ansible.builtin.include_role:
    name: "{{ roles.role }}"
    apply:
      tags: controller
  tags: controller
  loop_control:
    loop_var: roles
  loop:
    - role: ansible-common-role
    - role: ansible-nginx-role
    - role: ansible-nginx-enable-letsencrypt-role
    - role: ansible-certbot-role
    - role: ansible-clustercontrol-role
