---
- name: HAProxy service
  ansible.builtin.include_role:
    name: "{{ roles.role }}"
  loop_control:
    loop_var: roles
  loop:
    - role: ansible-common-role
    - role: ansible-haproxy-role
    - role: ansible-haproxy-lb-role