---
- name: Wordpress service
  ansible.builtin.include_role:
    name: "{{ roles.role }}"
  loop_control:
    loop_var: roles
  loop:
    - role: ansible-common-role
    - role: ansible-sendmail-role
    - role: ansible-phpmyadmin-role
    - role: ansible-certbot-role
    - role: ansible-nginx-enable-letsencrypt-role
    - role: ansible-wordpress-role
