---
- name: Wordpress service
  ansible.builtin.include_role:
    name: "{{ roles.role }}"
  loop_control:
    loop_var: roles
  loop:
    - role: cloudwm.ansible_cloudwm_collection.ansible-common-role
    - role: cloudwm.ansible_cloudwm_collection.ansible-sendmail-role
    - role: cloudwm.ansible_cloudwm_collection.ansible-phpmyadmin-role
    - role: cloudwm.ansible_cloudwm_collection.ansible-certbot-role
    - role: cloudwm.ansible_cloudwm_collection.ansible-nginx-enable-letsencrypt-role
    - role: cloudwm.ansible_cloudwm_collection.ansible-wordpress-role
